"""
fishtank.fish_types
-------------------
author: fishtank.py :)


This is a file generated by fish tank for easy access to fish types.
For more information, check out fishtank.fish_generator!
"""

# these classes are only used for organization purposes, and as such
# provide no class methods.
#
# pylint: disable=too-few-public-methods

from random import randint
from .enums import FishProperties, FishType


def random(cls: object) -> FishProperties:
    """ Return a random element from class """

    options = [
        attr for attr in dir(cls) if not attr.startswith("_") and not attr == "random"
    ]
    output = getattr(cls, options[randint(0, len(options) - 1)])

    # mypy complains that output is of type Any, but we know it cannot be.
    return output  # type: ignore


class Molly:
    """ Organizer class for variaties of Molly """

    Molly: FishProperties = {
        "stages": [">->", "><'>", ">-<'>"],
        "type": FishType.MID_WATER,
        "pigment": [232, 242],
        "speed": 3,
        "variant": "dalmatian",
        "species": "Molly",
        "pos": [0, 0],
        "age": 0,
    }

    Golden: FishProperties = {
        "stages": [">->", "><'>", ">-<'>"],
        "type": FishType.MID_WATER,
        "pigment": [214, 220, 221],
        "speed": 3,
        "variant": "golden",
        "species": "Molly",
        "pos": [0, 0],
        "age": 0,
        "chance": 5,
        "dominance": 30,
    }

    Golden_Panda: FishProperties = {
        "stages": [">->", "><'>", ">-<'>"],
        "type": FishType.MID_WATER,
        "pigment": [214, 220, 221, 232, 234],
        "speed": 3,
        "variant": "golden_panda",
        "species": "Molly",
        "pos": [0, 0],
        "age": 0,
        "chance": 15,
        "dominance": 30,
    }

    Silver: FishProperties = {
        "stages": [">->", "><'>", ">-<'>"],
        "type": FishType.MID_WATER,
        "pigment": [249, 252, 255],
        "speed": 3,
        "variant": "silver",
        "species": "Molly",
        "pos": [0, 0],
        "age": 0,
        "chance": 35,
        "dominance": 40,
    }

    Black: FishProperties = {
        "stages": [">->", "><'>", ">-<'>"],
        "type": FishType.MID_WATER,
        "pigment": [232, 233, 237],
        "speed": 3,
        "variant": "black",
        "species": "Molly",
        "pos": [0, 0],
        "age": 0,
        "chance": 70,
        "dominance": 60,
    }

    Dalmatian: FishProperties = {
        "stages": [">->", "><'>", ">-<'>"],
        "type": FishType.MID_WATER,
        "pigment": [232, 234, 235, 247, 251],
        "speed": 3,
        "variant": "dalmatian",
        "species": "Molly",
        "pos": [0, 0],
        "age": 0,
        "chance": 100,
        "dominance": 50,
    }

    Wobbly: FishProperties = {
        "stages": ["-", "-=", "-<>"],
        "type": FishType.MID_WATER,
        "pigment": [232, 242],
        "speed": 3,
        "variant": "dalmatian",
        "species": "Molly",
        "pos": [0, 0],
        "age": 2,
        "forced_pigment": [233, 234, 235],
        "message": "wobble wobble",
        "name": "wobbly",
    }

    Winona: FishProperties = {
        "stages": [">->", "><'>", ">-<'>"],
        "type": FishType.MID_WATER,
        "pigment": [232, 242],
        "speed": None,
        "variant": "dalmatian",
        "species": "Molly",
        "pos": [0, 0],
        "age": 1,
        "forced_pigment": [233, 232, 233, 253],
        "message": None,
        "name": "winona",
    }

    Ivory: FishProperties = {
        "stages": [">->", "><'>", ">-<'>"],
        "type": FishType.MID_WATER,
        "pigment": [232, 242],
        "speed": 3,
        "variant": "dalmatian",
        "species": "Molly",
        "pos": [0, 0],
        "age": 2,
        "forced_pigment": [255, 255, 255, 255, 255],
        "name": "ivory",
    }

    Jumbo: FishProperties = {
        "stages": [">->", "><'>", ">-<'>"],
        "type": FishType.MID_WATER,
        "pigment": [232, 242],
        "speed": 2,
        "variant": "dalmatian",
        "species": "Molly",
        "pos": [0, 0],
        "age": 2,
        "forced_pigment": [255, 255, 255, 255, 255],
        "name": "jumbo",
    }

    Goldie: FishProperties = {
        "stages": [".", ">-", "><>"],
        "type": FishType.MID_WATER,
        "pigment": [232, 242],
        "speed": 4,
        "variant": "dalmatian",
        "species": "Molly",
        "pos": [0, 0],
        "age": 2,
        "forced_pigment": [232, 232, 220],
        "name": "goldie",
    }

    Strength: FishProperties = {
        "stages": [">->", ">-=>", ">-<'>"],
        "type": FishType.MID_WATER,
        "pigment": [232, 242],
        "speed": 2,
        "variant": "dalmatian",
        "species": "Molly",
        "pos": [0, 0],
        "age": 1,
        "forced_pigment": [233, 232, 233, 232, 253],
        "name": "strength",
    }

    Mandarin: FishProperties = {
        "stages": [">->", "><'>", ">-<'>"],
        "type": FishType.MID_WATER,
        "pigment": [232, 242],
        "speed": 3,
        "variant": "dalmatian",
        "species": "Molly",
        "pos": [0, 0],
        "age": 2,
        "forced_pigment": [220, 220, 220, 220, 220],
        "name": "mandarin",
    }

    Sunny: FishProperties = {
        "stages": ["--", ">->", "><'>"],
        "type": FishType.MID_WATER,
        "pigment": [232, 242],
        "speed": 4,
        "variant": "dalmatian",
        "species": "Molly",
        "pos": [0, 0],
        "age": 1,
        "forced_pigment": [220, 220, 220, 220, 220],
        "name": "sunny",
    }

    Tiny: FishProperties = {
        "stages": [".", "=-", ">->"],
        "type": FishType.MID_WATER,
        "pigment": [232, 242],
        "speed": 5,
        "variant": "dalmatian",
        "species": "Molly",
        "pos": [0, 0],
        "age": 1,
        "forced_pigment": [240],
        "name": "tiny",
    }

    Baby: FishProperties = {
        "stages": [".", "=-", "><'>"],
        "type": FishType.MID_WATER,
        "pigment": [232, 242],
        "speed": 5,
        "variant": "dalmatian",
        "species": "Molly",
        "pos": [0, 0],
        "age": 1,
        "forced_pigment": [240],
        "name": "baby",
    }

    Mjoofin: FishProperties = {
        "stages": [".", "=-", "><>"],
        "type": FishType.MID_WATER,
        "pigment": [232, 242],
        "speed": 5,
        "variant": "dalmatian",
        "species": "Molly",
        "pos": [0, 0],
        "age": 1,
        "forced_pigment": [240, 240, 249],
        "name": "mjoofin",
    }


class Guppy:
    """ Organizer class for variaties of Guppy """

    Guppy: FishProperties = {
        "stages": [">=", "]=>", ")=>"],
        "type": FishType.MID_WATER,
        "speed": 4,
        "pigment": [141],
        "species": "Guppy",
        "pos": [0, 0],
        "age": 0,
    }

    Tuxedo: FishProperties = {
        "stages": [">=", "]=>", ")=>"],
        "type": FishType.MID_WATER,
        "speed": 4,
        "pigment": [232, 255],
        "species": "Guppy",
        "pos": [0, 0],
        "age": 0,
        "chance": 60,
        "dominance": 40,
        "variant": "tuxedo",
    }

    Blue: FishProperties = {
        "stages": [">=", "]=>", ")=>"],
        "type": FishType.MID_WATER,
        "speed": 4,
        "pigment": [104, 62, 111],
        "species": "Guppy",
        "pos": [0, 0],
        "age": 0,
        "chance": 80,
        "dominance": 30,
        "variant": "blue",
    }

    Green: FishProperties = {
        "stages": [">=", "]=>", ")=>"],
        "type": FishType.MID_WATER,
        "speed": 4,
        "pigment": [64, 106, 107],
        "species": "Guppy",
        "pos": [0, 0],
        "age": 0,
        "chance": 90,
        "dominance": 20,
        "variant": "green",
    }

    Panda: FishProperties = {
        "stages": [">=", "]=>", ")=>"],
        "type": FishType.MID_WATER,
        "speed": 4,
        "pigment": [104, 62, 232, 255],
        "species": "Guppy",
        "pos": [0, 0],
        "age": 0,
        "chance": 100,
        "dominance": 20,
        "variant": "panda",
    }


class Corydoras:
    """ Organizer class for variaties of Corydoras """

    Corydoras: FishProperties = {
        "stages": [">,-", ">,>", "><,>"],
        "type": FishType.BOTTOM_DWELLER,
        "pigment": [232, 251, 251, 232],
        "species": "Corydoras",
        "pos": [0, 0],
        "age": 0,
    }

    Panda: FishProperties = {
        "stages": [">,-", ">,>", "><,>"],
        "type": FishType.BOTTOM_DWELLER,
        "pigment": [232, 252, 252, 232],
        "species": "Corydoras",
        "pos": [0, 0],
        "age": 0,
        "chance": 100,
        "dominance": 100,
        "variant": "panda",
    }
